// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKjrfj-3ydhHa8ScaQTtsLYCEkmXioY8c',
    appId: '1:99804925924:web:ca7fc143cc32ffddcb81f1',
    messagingSenderId: '99804925924',
    projectId: 'gravdesinghub',
    authDomain: 'gravdesinghub.firebaseapp.com',
    storageBucket: 'gravdesinghub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCasp9SYrSjvDd8-v-WxxDW3NrwjEAsmAw',
    appId: '1:99804925924:android:b7b250f8ef1703d0cb81f1',
    messagingSenderId: '99804925924',
    projectId: 'gravdesinghub',
    storageBucket: 'gravdesinghub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrJyljcWw5jy5aYHI3sDULRmG2bGZxg7c',
    appId: '1:99804925924:ios:77dfd2fe59e4b0f8cb81f1',
    messagingSenderId: '99804925924',
    projectId: 'gravdesinghub',
    storageBucket: 'gravdesinghub.firebasestorage.app',
    iosBundleId: 'com.example.gravdesinghub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrJyljcWw5jy5aYHI3sDULRmG2bGZxg7c',
    appId: '1:99804925924:ios:77dfd2fe59e4b0f8cb81f1',
    messagingSenderId: '99804925924',
    projectId: 'gravdesinghub',
    storageBucket: 'gravdesinghub.firebasestorage.app',
    iosBundleId: 'com.example.gravdesinghub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKjrfj-3ydhHa8ScaQTtsLYCEkmXioY8c',
    appId: '1:99804925924:web:87f6a580e6cdac8fcb81f1',
    messagingSenderId: '99804925924',
    projectId: 'gravdesinghub',
    authDomain: 'gravdesinghub.firebaseapp.com',
    storageBucket: 'gravdesinghub.firebasestorage.app',
  );
}
